name: Helm Chart Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'latest'

      - name: Install KubeSec
        run: |
          curl -sSL https://github.com/controlplaneio/kubesec/releases/download/v2.11.2/kubesec_linux_amd64.tar.gz | tar xz
          sudo mv kubesec /usr/local/bin/

      - name: Run kubeSec on Helm Chart
        run: |
          helm template my-chart ./charts/my-chart | kubeSec score - > kubeSec-output.txt

      - name: Upload kubeSec Scan Output
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: kubeSec-scan-output
          path: kubeSec-output.txt

      - name: Post kubeSec Results to PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const output = fs.readFileSync(path.join(process.env.GITHUB_WORKSPACE, 'kubeSec-output.txt'), 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '**kubeSec Security Scan Results**\n```\n' + output + '\n```'
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

