
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-scan:
    # Specifies the runner environment
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checks out the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq


    # Step 2: Install Kubesec for security scanning
    - name: Install Kubesec
      run: |
        curl -sSL https://github.com/controlplaneio/kubesec/releases/download/v2.11.2/kubesec_linux_amd64.tar.gz | tar xz -C /tmp
        sudo mv /tmp/kubesec /usr/local/bin

    - name: Validate Kubernetes manifests
      id: kubesec
      run: |
        kubesec scan ./my-chart/*.yaml > kubesec_output.json && cat kubesec_output.json

    - name: Check validation result
      run: |
       if grep -q '"score":.*[[:space:]]-?[1-9]' kubesec_output.json; then
       echo "Some issues found in Kubernetes manifests. Fail the workflow."
        exit 2
       else
        echo "All Kubernetes manifests passed validation."
         fi


        



