
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-scan:
    # Specifies the runner environment
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checks out the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Install Kubesec for security scanning
    - name: Install Kubesec
      run: |
        curl -sSL https://github.com/controlplaneio/kubesec/releases/download/v2.11.2/kubesec_linux_amd64.tar.gz | tar xz -C /tmp
        sudo mv /tmp/kubesec /usr/local/bin

    - name: Scan and Parse Kubesec Score
      run: |
       output=$(kubesec scan ./my-charts/*.yaml)
       echo "$output"
       score=$(echo "$output" | jq '.[0].score' 2>/dev/null)
    
       if [ -z "$score" ] || [ "$score" == "null" ]; then
       echo "Failed to parse score or Kubesec output is not JSON"
       exit 1
       fi
    
       echo "Kubesec score: $score"
       echo "KUBESCORE=$score" >> $GITHUB_ENV
       if [ "$score" -lt 0 ]; then
       echo "Security scan did not pass."
       exit 1
       fi

