
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Kubesec
        run: |
          curl -sSL https://github.com/controlplaneio/kubesec/releases/download/v2.11.2/kubesec_linux_amd64.tar.gz | tar xz -C /tmp
          sudo mv /tmp/kubesec /usr/local/bin
      
      - name: Scan Kubernetes manifests and check score
        run: |
         output=$(kubesec scan ./my-chart/*.yaml)
         echo "$output"
         if [ -z "$output" ]; then
         echo "Kubesec output is empty"
         exit 1
          fi
         score=$(echo "$output" | jq '.[0].score')
         echo "Kubesec score: $score"
         echo "KUBESCORE=$score" >> $GITHUB_ENV
         if [ "$score" -lt 5 ]; then
         echo "Security scan did not pass."
         exit 1
          fi



